site_name: Red Hat OpenShift and IBM Cloud Paks on IBM Z and LinuxONE Workshop
repo_url: https://github.com/mmondics/ocp-cloudpak-workshop/
site_url: https://mmondics.github.io/ocp-cloudpak-workshop/
edit_uri: edit/main/docs

nav:
    - Home: 'index.md'
    - Prerequisites: 'prerequisites.md'
    - Lab Assignments: 'lab-assignments.md'
    - Presentations:
      - Presentation 1: presentations/presentation1.pdf
      - Presentation 2: presentations/presentation2.pdf
    - Labs: 
      - Lab 001: 
        - Introduction: 'lab001-1.md'
        - Connect to OCP: 'lab001-2.md'
        - The Administrator Persepctive: 'lab001-3.md'
        - The Developer Perspective: 'lab001-4.md'
        - Deploy from the Developer Catalog: 'lab001-5.md'
        - View Workload from the Administrator Perspective: 'lab001-6.md'
        - Cleaning Up: 'lab001-7.md'
      - Lab 002: 
        - Introduction: 'lab002-1.md'
        - Log into OpenShift Using the CLI: 'lab002-2.md'
        - Overview of the OpenShift CLI: 'lab002-3.md'
        - Deploy Container Image from the CLI: 'lab002-4.md'
        - Open a Remote Shell Session into the MongoDB Pod: 'lab002-5.md'
        - Working with Pods: 'lab002-6.md'
        - Administrative CLI Commands: 'lab002-7.md'
        - Cleaning Up: 'lab002-8.md'
      - Lab 003: 
        - Introduction: 'lab003-1.md'
        - Connect to OCP: 'lab003-2.md'
        - Deploy Liberty for z/OS Using the z/OS Cloud Broker: 'lab003-3.md'
        - Stop and Restart Liberty for z/OS from OCP: 'lab003-4.md'
        - Cleaning Up: 'lab003-5.md'
      - Lab 004:
        - Source-to-Image (S2I) Overview: 'lab004-1.md'
        - Exploring GitHub and the Example Health Source Code: 'lab004-2.md'
        - Connect to OCP and Authenticate: 'lab004-3.md'
        - Edit the Source Code and Push an Update: 'lab004-4.md'
        - Cleaning Up: 'lab004-5.md'
      - Lab 005:
        - Overview of OpenShift Monitoring: 'lab005-1.md'
        - Connect to OCP and Authenticate: 'lab005-2.md'
        - Using OpenShift Metrics (Prometheus): 'lab005-3.md'
        - Using the In-Browser Grafana Dashboards: 'lab005-4.md'
        - Connect to Grafana: 'lab005-5.md'
        - Using Grafana Dashboards: 'lab005-6.md'
        - Using OpenShift Alerts (Alertmanager): 'lab005-7.md'
      - Lab 006:
        - Overview of Persistent Storage and Application Architecture: 'lab006-1.md'
        - Connect to OCP and Authenticate: 'lab006-2.md'
        - Create a PersistentVolumeClaim: 'lab006-3.md'
        - Deploy MongoDB from Container Image: 'lab006-4.md'
        - Deploy Node.js Application from Dockerfile: 'lab006-5.md'
        - Interacting with MongoDB from Node.js Application: 'lab006-6.md'
        - Cleaning Up: 'lab006-7.md'
      - Lab 007:
        - Overview of the Open Liberty Operator and Sample Application: 'lab007-1.md'
        - Log into OpenShift Using the CLI: 'lab007-2.md'
        - Cloning the GitHub Repository and Reviewing its Contents: 'lab007-3.md'
        - Using the Open Liberty Operator to Install an Application: 'lab007-4.md'
        - Access the Application in a Browser: 'lab007-5.md'
        - Cleaning Up: 'lab007-6.md'
      - Lab 008:
        - Overview of the Quarkus Red Hat Runtime: 'lab008-1.md'
        - Log into OpenShift Using the CLI: 'lab008-2.md'
        - Creating and Reviewing the Quarkus Project: 'lab008-3.md'
        - Configure the Application for OpenShift: 'lab008-4.md'
        - Deploy the Application onto OpenShift: 'lab008-5.md'
        - Cleaning Up: 'lab008-6.md'
      - Lab 009:
        - Log into OpenShift Using the CLI: 'lab009-1.md'
        - Cloning the GitHub Repository and Viewing its Contents: 'lab009-2.md'
        - Understanding and Deploying Tasks: 'lab009-3.md'
        - Understanding and Deploying Pipelines: 'lab009-4.md'
        - Running the Pipeline: 'lab009-5.md'
        - Access the Application in a Browser: 'lab009-6.md'
        - Cleaning Up: 'lab009-7.md'
      - Lab 010:
        - Overview of the OpenShift Service Mesh: 'lab010-1.md'
        - OpenShift Service Mesh Architecture: 'lab010-2.md'
        - Log into OpenShift Using the CLI: 'lab010-3.md'
        - Cloning the GitHub Repository and Reviewing its Contents: 'lab010-4.md'
        - Deploying an Application on the Service Mesh: 'lab010-5.md'
        - Understanding and Deploying a Service Mesh Gateway and Virtual Service: 'lab010-6.md'
        - Traffic Management: 'lab010-7.md'
        - Application Observability with Kiali: 'lab010-8.md'
        - Distributed Tracing with Jaeger: 'lab010-9.md'
        - Wrap Up & Clean Up: 'lab010-10.md'

theme: 
  name: material
  palette:
    scheme: preference
  favicon: images/openshift-logo.png
  logo: images/openshift-logo.png

plugins:
  - search
#  - enumerate-headings:
#      toc_depth: 6
#      strict: true
  - print-site:
      add_to_navigation: true

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - attr_list
  - toc:
      permalink: true