site_name: Red Hat OpenShift and IBM Cloud Paks on IBM Z and LinuxONE Workshop
repo_url: https://github.com/mmondics/ocp-cloudpak-workshop/
site_url: https://mmondics.github.io/ocp-cloudpak-workshop/
edit_uri: edit/main/docs

nav:
    - Home: 'index.md'
    - Lab Assignments: 'lab-assignments.md'
    - Presentations:
      - Presentation 1: presentations/presentation1.pdf
      - Presentation 2: presentations/presentation2.pdf
    - Labs: 
      - Lab 001: 
        - Introduction: 'lab001-1.md'
        - Connect to OCP: 'lab001-2.md'
        - The Administrator Persepctive: 'lab001-3.md'
        - The Developer Perspective: 'lab001-4.md'
        - Deploy from the Developer Catalog: 'lab001-5.md'
        - View Workload from the Administrator Perspective: 'lab001-6.md'
        - Cleaning Up: 'lab001-7.md'
      - Lab 002: 
        - Introduction: 'lab002-1.md'
        - Log into OpenShift Using the CLI: 'lab002-2.md'
        - Overview of the OpenShift CLI: 'lab002-3.md'
        - Deploy Container Image from the CLI: 'lab002-4.md'
        - Open a Remote Shell Session into the MongoDB Pod: 'lab002-5.md'
        - Working with Pods: 'lab002-6.md'
        - Administrative CLI Commands: 'lab002-7.md'
        - Cleaning Up: 'lab002-8.md'
      - Lab 003: 
        - Introduction: 'lab003-1.md'
        - Connect to OCP: 'lab003-2.md'
        - Deploy Liberty for z/OS Using the z/OS Cloud Broker: 'lab003-3.md'
        - Stop and Restart Liberty for z/OS from OCP: 'lab003-4.md'
        - Cleaning Up: 'lab003-5.md'
      - Lab 004:
        - Source-to-Image (S2I) Overview: 'lab004-1.md'
        - Exploring GitHub and the Example Health Source Code: 'lab004-2.md'
        - Connect to OCP and Authenticate: 'lab004-3.md'
        - Edit the Source Code and Push an Update: 'lab004-4.md'
        - Cleaning Up: 'lab004-5.md'
      - Lab 005:
        - Overview of OpenShift Monitoring: 'lab005-1.md'
        - Connect to OCP and Authenticate: 'lab005-2.md'
        - Using OpenShift Metrics (Prometheus): 'lab005-3.md'
        - Using the In-Browser Grafana Dashboards: 'lab005-4.md'
        - Connect to Grafana: 'lab005-5.md'
        - Using Grafana Dashboards: 'lab005-6.md'
        - Using OpenShift Alerts (Alertmanager): 'lab005-7.md'
      - Lab 006: 'lab006-1.md'
      - Lab 007: 'lab007-1.md'
      - Lab 008: 'lab008-1.md'
      - Lab 009: 'lab009-1.md'
      - Lab 010: 'lab010-1.md'

theme: 
  name: material
  palette:
    scheme: preference
  favicon: images/openshift-logo.png
  logo: images/openshift-logo.png

plugins:
  - search
#  - enumerate-headings:
#      toc_depth: 6
#      strict: true
  - print-site:
      add_to_navigation: true

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - attr_list
  - toc:
      permalink: true