site_name: Red Hat OpenShift and IBM Cloud Paks on IBM Z and LinuxONE Workshop
repo_url: https://github.com/mmondics/ocp-cloudpak-workshop/
site_url: https://mmondics.github.io/ocp-cloudpak-workshop/
edit_uri: edit/main/docs

nav:
    - Home: 'index.md'
    - Presentations:
      - Presentation 1: presentations/presentation1.pdf
      - Presentation 2: presentations/presentation2.pdf
    - Labs: 
      - Lab 001: 'lab001.md'
      - Lab 002: 'lab002.md'
      - Lab 003: 'lab003.md'
      - Lab 004: 'lab004.md'
      - Lab 005: 'lab005.md'
      - Lab 006: 'lab006.md'
      - Lab 007: 'lab007.md'
      - Lab 008: 'lab008.md'
      - Lab 009: 'lab009.md'
      - Lab 010: 'lab010.md'

theme: 
  name: material
  palette:
    scheme: preference
  favicon: images/openshift-logo.png
  logo: images/openshift-logo.png

plugins:
  - search
#  - enumerate-headings:
#      toc_depth: 6
#      strict: true
  - print-site:
      add_to_navigation: true