site_name: Red Hat OpenShift and IBM Cloud Paks on IBM Z and LinuxONE Workshop
edit_uri: edit/main/docs

nav:
    - Home: 'index.md'
    - Lab 001: 'lab001.md'

theme:
    name: material

plugins:
#  - search
  - print-site:
      add_to_navigation: true